name: Monday Quote

on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  send-quote:
    runs-on: ubuntu-latest

    env:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install pandas

      - run: python main.py

      - run: pip install pandas

      - run: python main.py
